"""modify-3

Revision ID: 1e9086989e95
Revises: e734e62db5a7
Create Date: 2017-10-13 15:28:51.788000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e9086989e95'
down_revision = 'e734e62db5a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_user', sa.Column('up_time', sa.TIMESTAMP(), nullable=True))
    op.drop_column('test_user', 'update_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_user', sa.Column('update_time', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('test_user', 'up_time')
    # ### end Alembic commands ###
