"""init pay_project

Revision ID: 1fae0df53424
Revises: 1e9086989e95
Create Date: 2017-10-13 19:03:22.922000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fae0df53424'
down_revision = '1e9086989e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('agent_fee', sa.Integer(), nullable=True),
    sa.Column('selling_fee', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('order_index', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pay_project_order_index'), 'pay_project', ['order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pay_project_order_index'), table_name='pay_project')
    op.drop_table('pay_project')
    # ### end Alembic commands ###
