"""empty message

Revision ID: 2a8c8ed9a6d7
Revises: 42a71bb8b244
Create Date: 2017-10-19 16:09:56.558000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8c8ed9a6d7'
down_revision = '42a71bb8b244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_order', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('pay_order', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pay_order', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pay_order', type_='foreignkey')
    op.drop_column('pay_order', 'user_id')
    op.drop_column('pay_order', 'deleted')
    # ### end Alembic commands ###