"""modify
Revision ID: 4155c90360ac
Revises: f164e91a98a3
Create Date: 2017-10-13 15:23:27.605000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4155c90360ac'
down_revision = 'f164e91a98a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_role', sa.Column('up_time', sa.TIMESTAMP(), nullable=True))
    op.drop_column('test_role', 'update_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_role', sa.Column('update_time', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('test_role', 'up_time')
    # ### end Alembic commands ###