"""empty message

Revision ID: 42a71bb8b244
Revises: fde3d01ad69f
Create Date: 2017-10-19 14:59:27.217000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a71bb8b244'
down_revision = 'fde3d01ad69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('up_time', sa.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'upda_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('upda_time', mysql.TIMESTAMP(), server_default=sa.text(u"'0000-00-00 00:00:00'"), nullable=False))
    op.drop_column('user', 'up_time')
    # ### end Alembic commands ###