"""empty message

Revision ID: e0b013b21bef
Revises: fc508d368481
Create Date: 2017-10-25 16:14:00.836000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b013b21bef'
down_revision = 'fc508d368481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expire_time', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('login_last_ip', sa.String(length=64), server_default='', nullable=True))
    op.add_column('user', sa.Column('login_last_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_last_time')
    op.drop_column('user', 'login_last_ip')
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'expire_time')
    # ### end Alembic commands ###