"""modify-2
Revision ID: e734e62db5a7
Revises: 4155c90360ac
Create Date: 2017-10-13 15:26:40.192000
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e734e62db5a7'
down_revision = '4155c90360ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_role', sa.Column('update_time', sa.TIMESTAMP(), nullable=True))
    op.drop_column('test_role', 'up_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_role', sa.Column('up_time', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('test_role', 'update_time')
    # ### end Alembic commands ###