"""empty message

Revision ID: fc508d368481
Revises: 2a8c8ed9a6d7
Create Date: 2017-10-25 14:54:44.607000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc508d368481'
down_revision = '2a8c8ed9a6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_project', sa.Column('all_agent_fee', sa.Integer(), nullable=True))
    op.add_column('pay_project', sa.Column('normal_agent_fee', sa.Integer(), nullable=True))
    op.drop_column('pay_project', 'agent_fee')
    op.add_column('user', sa.Column('level', sa.String(length=32), server_default='normal', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'level')
    op.add_column('pay_project', sa.Column('agent_fee', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('pay_project', 'normal_agent_fee')
    op.drop_column('pay_project', 'all_agent_fee')
    # ### end Alembic commands ###